apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ticketing

build:
  artifacts:
    - image: emadunan/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
        noCache: true
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: emadunan/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "**/*.js"
    - image: emadunan/ticketing-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
  local:
    push: false

manifests:
  rawYaml:
    - k8s/*
deploy:
  kubectl: {}
